export type PlannerRolloutStage = "core" | "top10" | "wave1" | "wave2" | "wave3" | "wave4";
export type PlannerReadinessTier = "full" | "planner_ready" | "prepared";
export type PlannerVisibility = "visible" | "hidden";

export type PlannerRolloutCity = {
  slug: string;
  label: string;
  countryCode: string;
  lat: number;
  lng: number;
  radiusM: number;
  stage: PlannerRolloutStage;
  readinessTier: PlannerReadinessTier;
  plannerVisibility: PlannerVisibility;
  aliasSlugs?: string[];
};

export const PLANNER_VISIBILITY_GATES = {
  minimumPlannableLocations: 250,
  minimumFoodLocations: 120,
  minimumScheduledEvents: 12,
  requiresActiveOfficialEventSource: true,
} as const;

export const PLANNER_33_ROLLOUT: PlannerRolloutCity[] = [
  {
    slug: "berlin-berlin",
    label: "Berlin",
    countryCode: "DE",
    lat: 52.520008,
    lng: 13.404954,
    radiusM: 18000,
    stage: "core",
    readinessTier: "full",
    plannerVisibility: "visible",
  },
  {
    slug: "hamburg-hamburg",
    label: "Hamburg",
    countryCode: "DE",
    lat: 53.551086,
    lng: 9.993682,
    radiusM: 18000,
    stage: "core",
    readinessTier: "full",
    plannerVisibility: "visible",
  },
  {
    slug: "muenchen",
    label: "Muenchen",
    countryCode: "DE",
    lat: 48.137154,
    lng: 11.576124,
    radiusM: 16000,
    stage: "core",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["muenchen-freistaat-bayern", "muenchen-bayern"],
  },
  {
    slug: "koeln",
    label: "Koeln",
    countryCode: "DE",
    lat: 50.9422,
    lng: 6.9578,
    radiusM: 18000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["koeln-nordrhein-westfalen"],
  },
  {
    slug: "frankfurt-am-main",
    label: "Frankfurt am Main",
    countryCode: "DE",
    lat: 50.1106,
    lng: 8.6822,
    radiusM: 16000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["frankfurt-am-main-hessen"],
  },
  {
    slug: "stuttgart",
    label: "Stuttgart",
    countryCode: "DE",
    lat: 48.7775,
    lng: 9.18,
    radiusM: 16000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["stuttgart-baden-wuerttemberg", "stuttgart-baden-w-rttemberg"],
  },
  {
    slug: "duesseldorf",
    label: "Duesseldorf",
    countryCode: "DE",
    lat: 51.2311,
    lng: 6.7724,
    radiusM: 15000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["duesseldorf-nordrhein-westfalen"],
  },
  {
    slug: "leipzig",
    label: "Leipzig",
    countryCode: "DE",
    lat: 51.34,
    lng: 12.375,
    radiusM: 16000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["leipzig-freistaat-sachsen", "leipzig-sachsen"],
  },
  {
    slug: "dresden",
    label: "Dresden",
    countryCode: "DE",
    lat: 51.05,
    lng: 13.74,
    radiusM: 16000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["dresden-sachsen"],
  },
  {
    slug: "hannover",
    label: "Hannover",
    countryCode: "DE",
    lat: 52.3744,
    lng: 9.7386,
    radiusM: 15000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["hannover-niedersachsen"],
  },
  {
    slug: "nuernberg",
    label: "Nuernberg",
    countryCode: "DE",
    lat: 49.4539,
    lng: 11.0775,
    radiusM: 15000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["nuernberg-bayern"],
  },
  {
    slug: "bremen",
    label: "Bremen",
    countryCode: "DE",
    lat: 53.0758,
    lng: 8.8072,
    radiusM: 16000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["bremen-freie-hansestadt-bremen"],
  },
  {
    slug: "dortmund",
    label: "Dortmund",
    countryCode: "DE",
    lat: 51.5139,
    lng: 7.4653,
    radiusM: 17000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["dortmund-nordrhein-westfalen"],
  },
  {
    slug: "essen",
    label: "Essen",
    countryCode: "DE",
    lat: 51.4556,
    lng: 7.0116,
    radiusM: 15000,
    stage: "wave1",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["essen-nordrhein-westfalen"],
  },
  {
    slug: "bonn",
    label: "Bonn",
    countryCode: "DE",
    lat: 50.7374,
    lng: 7.0982,
    radiusM: 14000,
    stage: "wave1",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["bonn-nordrhein-westfalen"],
  },
  {
    slug: "muenster",
    label: "Muenster",
    countryCode: "DE",
    lat: 51.9624,
    lng: 7.6257,
    radiusM: 14000,
    stage: "wave1",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["muenster-nordrhein-westfalen"],
  },
  {
    slug: "mannheim",
    label: "Mannheim",
    countryCode: "DE",
    lat: 49.4875,
    lng: 8.466,
    radiusM: 14000,
    stage: "wave1",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["mannheim-baden-wuerttemberg", "mannheim-baden-w-rttemberg"],
  },
  {
    slug: "wiesbaden",
    label: "Wiesbaden",
    countryCode: "DE",
    lat: 50.0826,
    lng: 8.24,
    radiusM: 14000,
    stage: "wave1",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["wiesbaden-hessen"],
  },
  {
    slug: "aachen",
    label: "Aachen",
    countryCode: "DE",
    lat: 50.7753,
    lng: 6.0839,
    radiusM: 14000,
    stage: "wave1",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["aachen-nordrhein-westfalen"],
  },
  {
    slug: "karlsruhe",
    label: "Karlsruhe",
    countryCode: "DE",
    lat: 49.0069,
    lng: 8.4037,
    radiusM: 14000,
    stage: "wave1",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["karlsruhe-baden-wuerttemberg", "karlsruhe-baden-w-rttemberg"],
  },
  {
    slug: "duisburg",
    label: "Duisburg",
    countryCode: "DE",
    lat: 51.4344,
    lng: 6.7623,
    radiusM: 15000,
    stage: "wave2",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["duisburg-nordrhein-westfalen"],
  },
  {
    slug: "bochum",
    label: "Bochum",
    countryCode: "DE",
    lat: 51.4818,
    lng: 7.2162,
    radiusM: 14000,
    stage: "wave2",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["bochum-nordrhein-westfalen"],
  },
  {
    slug: "wuppertal",
    label: "Wuppertal",
    countryCode: "DE",
    lat: 51.2562,
    lng: 7.1508,
    radiusM: 15000,
    stage: "wave2",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["wuppertal-nordrhein-westfalen"],
  },
  {
    slug: "bielefeld",
    label: "Bielefeld",
    countryCode: "DE",
    lat: 52.0212,
    lng: 8.5347,
    radiusM: 15000,
    stage: "wave2",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["bielefeld-nordrhein-westfalen"],
  },
  {
    slug: "augsburg",
    label: "Augsburg",
    countryCode: "DE",
    lat: 48.3705,
    lng: 10.8978,
    radiusM: 14000,
    stage: "wave2",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["augsburg-bayern"],
  },
  {
    slug: "braunschweig",
    label: "Braunschweig",
    countryCode: "DE",
    lat: 52.2689,
    lng: 10.5268,
    radiusM: 14000,
    stage: "wave2",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["braunschweig-niedersachsen"],
  },
  {
    slug: "kiel",
    label: "Kiel",
    countryCode: "DE",
    lat: 54.3233,
    lng: 10.1228,
    radiusM: 15000,
    stage: "wave2",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["kiel-schleswig-holstein"],
  },
  {
    slug: "gelsenkirchen",
    label: "Gelsenkirchen",
    countryCode: "DE",
    lat: 51.5177,
    lng: 7.0857,
    radiusM: 14000,
    stage: "wave3",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["gelsenkirchen-nordrhein-westfalen"],
  },
  {
    slug: "moenchengladbach",
    label: "Moenchengladbach",
    countryCode: "DE",
    lat: 51.1805,
    lng: 6.4428,
    radiusM: 14000,
    stage: "wave3",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["moenchengladbach-nordrhein-westfalen"],
  },
  {
    slug: "magdeburg",
    label: "Magdeburg",
    countryCode: "DE",
    lat: 52.1205,
    lng: 11.6276,
    radiusM: 15000,
    stage: "wave3",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["magdeburg-sachsen-anhalt"],
  },
  {
    slug: "freiburg-im-breisgau",
    label: "Freiburg im Breisgau",
    countryCode: "DE",
    lat: 47.999,
    lng: 7.8421,
    radiusM: 14000,
    stage: "wave3",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: [
      "freiburg-im-breisgau-baden-wuerttemberg",
      "freiburg-im-breisgau-baden-w-rttemberg",
    ],
  },
  {
    slug: "luebeck",
    label: "Luebeck",
    countryCode: "DE",
    lat: 53.8655,
    lng: 10.6866,
    radiusM: 14000,
    stage: "wave3",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["luebeck-schleswig-holstein"],
  },
  {
    slug: "erfurt",
    label: "Erfurt",
    countryCode: "DE",
    lat: 50.9787,
    lng: 11.0328,
    radiusM: 14000,
    stage: "wave3",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["erfurt-thueringen"],
  },
  // Wave 4 — Großstädte 100k–250k aus Wikipedia-Liste, noch nicht aktiv im Planner.
  // plannerVisibility: hidden bis Locations-Ingest abgeschlossen ist.
  {
    slug: "chemnitz",
    label: "Chemnitz",
    countryCode: "DE",
    lat: 50.8278,
    lng: 12.9214,
    radiusM: 13000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["chemnitz-sachsen"],
  },
  {
    slug: "krefeld",
    label: "Krefeld",
    countryCode: "DE",
    lat: 51.3388,
    lng: 6.5853,
    radiusM: 13000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["krefeld-nordrhein-westfalen"],
  },
  {
    slug: "halle",
    label: "Halle (Saale)",
    countryCode: "DE",
    lat: 51.4828,
    lng: 11.9697,
    radiusM: 13000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["halle-sachsen-anhalt", "halle-saale", "halle-saale-sachsen-anhalt"],
  },
  {
    slug: "mainz",
    label: "Mainz",
    countryCode: "DE",
    lat: 49.9929,
    lng: 8.2473,
    radiusM: 13000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["mainz-rheinland-pfalz"],
  },
  {
    slug: "oberhausen",
    label: "Oberhausen",
    countryCode: "DE",
    lat: 51.4965,
    lng: 6.8628,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["oberhausen-nordrhein-westfalen"],
  },
  {
    slug: "rostock",
    label: "Rostock",
    countryCode: "DE",
    lat: 54.0833,
    lng: 12.1333,
    radiusM: 13000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["rostock-mecklenburg-vorpommern"],
  },
  {
    slug: "kassel",
    label: "Kassel",
    countryCode: "DE",
    lat: 51.3127,
    lng: 9.4797,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["kassel-hessen"],
  },
  {
    slug: "hagen",
    label: "Hagen",
    countryCode: "DE",
    lat: 51.3671,
    lng: 7.4633,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["hagen-nordrhein-westfalen"],
  },
  {
    slug: "potsdam",
    label: "Potsdam",
    countryCode: "DE",
    lat: 52.4009,
    lng: 13.0591,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["potsdam-brandenburg"],
  },
  {
    slug: "saarbruecken",
    label: "Saarbrücken",
    countryCode: "DE",
    lat: 49.2402,
    lng: 6.9969,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["saarbruecken-saarland", "saarbr-cken-saarland"],
  },
  {
    slug: "hamm",
    label: "Hamm",
    countryCode: "DE",
    lat: 51.6739,
    lng: 7.8158,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["hamm-nordrhein-westfalen"],
  },
  {
    slug: "ludwigshafen-am-rhein",
    label: "Ludwigshafen am Rhein",
    countryCode: "DE",
    lat: 49.4775,
    lng: 8.4454,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["ludwigshafen-rheinland-pfalz", "ludwigshafen-am-rhein-rheinland-pfalz"],
  },
  {
    slug: "oldenburg",
    label: "Oldenburg",
    countryCode: "DE",
    lat: 53.1435,
    lng: 8.2146,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["oldenburg-niedersachsen"],
  },
  {
    slug: "muelheim-an-der-ruhr",
    label: "Mülheim an der Ruhr",
    countryCode: "DE",
    lat: 51.4275,
    lng: 6.8823,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["muelheim-nordrhein-westfalen", "muelheim-an-der-ruhr-nordrhein-westfalen"],
  },
  {
    slug: "leverkusen",
    label: "Leverkusen",
    countryCode: "DE",
    lat: 51.0459,
    lng: 6.9883,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["leverkusen-nordrhein-westfalen"],
  },
  {
    slug: "darmstadt",
    label: "Darmstadt",
    countryCode: "DE",
    lat: 49.8728,
    lng: 8.6512,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["darmstadt-hessen"],
  },
  {
    slug: "osnabrueck",
    label: "Osnabrück",
    countryCode: "DE",
    lat: 52.2799,
    lng: 8.0472,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["osnabrueck-niedersachsen", "osnabr-ck-niedersachsen"],
  },
  {
    slug: "solingen",
    label: "Solingen",
    countryCode: "DE",
    lat: 51.1722,
    lng: 7.0832,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["solingen-nordrhein-westfalen"],
  },
  {
    slug: "herne",
    label: "Herne",
    countryCode: "DE",
    lat: 51.5388,
    lng: 7.2256,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["herne-nordrhein-westfalen"],
  },
  {
    slug: "paderborn",
    label: "Paderborn",
    countryCode: "DE",
    lat: 51.7189,
    lng: 8.7575,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["paderborn-nordrhein-westfalen"],
  },
  {
    slug: "heidelberg",
    label: "Heidelberg",
    countryCode: "DE",
    lat: 49.3988,
    lng: 8.6724,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["heidelberg-baden-wuerttemberg", "heidelberg-baden-w-rttemberg"],
  },
  {
    slug: "neuss",
    label: "Neuss",
    countryCode: "DE",
    lat: 51.2042,
    lng: 6.6878,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["neuss-nordrhein-westfalen"],
  },
  {
    slug: "regensburg",
    label: "Regensburg",
    countryCode: "DE",
    lat: 49.0134,
    lng: 12.1016,
    radiusM: 12000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["regensburg-bayern", "regensburg-freistaat-bayern"],
  },
  {
    slug: "ingolstadt",
    label: "Ingolstadt",
    countryCode: "DE",
    lat: 48.7665,
    lng: 11.4257,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["ingolstadt-bayern", "ingolstadt-freistaat-bayern"],
  },
  {
    slug: "pforzheim",
    label: "Pforzheim",
    countryCode: "DE",
    lat: 48.8915,
    lng: 8.6997,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["pforzheim-baden-wuerttemberg", "pforzheim-baden-w-rttemberg"],
  },
  {
    slug: "wuerzburg",
    label: "Würzburg",
    countryCode: "DE",
    lat: 49.7913,
    lng: 9.9534,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["wuerzburg-bayern", "w-rzburg-bayern"],
  },
  {
    slug: "offenbach-am-main",
    label: "Offenbach am Main",
    countryCode: "DE",
    lat: 50.1006,
    lng: 8.7665,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["offenbach-hessen", "offenbach-am-main-hessen"],
  },
  {
    slug: "heilbronn",
    label: "Heilbronn",
    countryCode: "DE",
    lat: 49.1427,
    lng: 9.2109,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["heilbronn-baden-wuerttemberg", "heilbronn-baden-w-rttemberg"],
  },
  {
    slug: "fuerth",
    label: "Fürth",
    countryCode: "DE",
    lat: 49.4778,
    lng: 10.9886,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["fuerth-bayern", "f-rth-bayern"],
  },
  {
    slug: "goettingen",
    label: "Göttingen",
    countryCode: "DE",
    lat: 51.5413,
    lng: 9.9158,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["goettingen-niedersachsen", "g-ttingen-niedersachsen"],
  },
  {
    slug: "ulm",
    label: "Ulm",
    countryCode: "DE",
    lat: 48.4011,
    lng: 9.9876,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["ulm-baden-wuerttemberg", "ulm-baden-w-rttemberg"],
  },
  {
    slug: "wolfsburg",
    label: "Wolfsburg",
    countryCode: "DE",
    lat: 52.4227,
    lng: 10.7865,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["wolfsburg-niedersachsen"],
  },
  {
    slug: "reutlingen",
    label: "Reutlingen",
    countryCode: "DE",
    lat: 48.4914,
    lng: 9.2043,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["reutlingen-baden-wuerttemberg", "reutlingen-baden-w-rttemberg"],
  },
  {
    slug: "bremerhaven",
    label: "Bremerhaven",
    countryCode: "DE",
    lat: 53.5396,
    lng: 8.5810,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["bremerhaven-bremen", "bremerhaven-freie-hansestadt-bremen"],
  },
  {
    slug: "bottrop",
    label: "Bottrop",
    countryCode: "DE",
    lat: 51.5237,
    lng: 6.9229,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["bottrop-nordrhein-westfalen"],
  },
  {
    slug: "erlangen",
    label: "Erlangen",
    countryCode: "DE",
    lat: 49.5896,
    lng: 11.0070,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["erlangen-bayern"],
  },
  {
    slug: "recklinghausen",
    label: "Recklinghausen",
    countryCode: "DE",
    lat: 51.6125,
    lng: 7.1969,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["recklinghausen-nordrhein-westfalen"],
  },
  {
    slug: "koblenz",
    label: "Koblenz",
    countryCode: "DE",
    lat: 50.3569,
    lng: 7.5890,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["koblenz-rheinland-pfalz"],
  },
  {
    slug: "remscheid",
    label: "Remscheid",
    countryCode: "DE",
    lat: 51.1789,
    lng: 7.1925,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["remscheid-nordrhein-westfalen"],
  },
  {
    slug: "bergisch-gladbach",
    label: "Bergisch Gladbach",
    countryCode: "DE",
    lat: 50.9856,
    lng: 7.1322,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["bergisch-gladbach-nordrhein-westfalen"],
  },
  {
    slug: "jena",
    label: "Jena",
    countryCode: "DE",
    lat: 50.9272,
    lng: 11.5859,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["jena-thueringen", "jena-th-ringen"],
  },
  {
    slug: "salzgitter",
    label: "Salzgitter",
    countryCode: "DE",
    lat: 52.1532,
    lng: 10.4146,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["salzgitter-niedersachsen"],
  },
  {
    slug: "trier",
    label: "Trier",
    countryCode: "DE",
    lat: 49.7567,
    lng: 6.6411,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["trier-rheinland-pfalz"],
  },
  {
    slug: "siegen",
    label: "Siegen",
    countryCode: "DE",
    lat: 50.8806,
    lng: 8.0211,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["siegen-nordrhein-westfalen"],
  },
  {
    slug: "moers",
    label: "Moers",
    countryCode: "DE",
    lat: 51.4567,
    lng: 6.6260,
    radiusM: 11000,
    stage: "wave4",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["moers-nordrhein-westfalen"],
  },
];

export const PLANNER_33_ROLLOUT_MAP = new Map(
  PLANNER_33_ROLLOUT.map((city) => [city.slug, city] satisfies [string, PlannerRolloutCity])
);

export const PLANNER_VISIBLE_CITY_ROLLOUT = PLANNER_33_ROLLOUT.filter(
  (city) => city.plannerVisibility === "visible"
);

export const PLANNER_VISIBLE_CITY_SLUGS = PLANNER_VISIBLE_CITY_ROLLOUT.map((city) => city.slug);

export const PLANNER_33_CITY_CONFIGS = Object.fromEntries(
  PLANNER_33_ROLLOUT.map((city) => [
    city.slug,
    {
      slug: city.slug,
      label: city.label,
      countryCode: city.countryCode,
      lat: city.lat,
      lng: city.lng,
      radiusM: city.radiusM,
    },
  ])
) as Record<
  string,
  Pick<PlannerRolloutCity, "slug" | "label" | "countryCode" | "lat" | "lng" | "radiusM">
>;

export function getPlannerRolloutCity(slug: string | null | undefined) {
  if (!slug) return null;
  return PLANNER_33_ROLLOUT_MAP.get(slug) ?? null;
}

export function getPlannerRolloutCitiesByStage(stage: PlannerRolloutStage) {
  return PLANNER_33_ROLLOUT.filter((city) => city.stage === stage);
}

export function getPreparedPlannerRolloutCities() {
  return PLANNER_33_ROLLOUT.filter((city) => city.plannerVisibility === "hidden");
}
