export type PlannerRolloutStage = "core" | "top10" | "wave1" | "wave2" | "wave3";
export type PlannerReadinessTier = "full" | "planner_ready" | "prepared";
export type PlannerVisibility = "visible" | "hidden";

export type PlannerRolloutCity = {
  slug: string;
  label: string;
  countryCode: string;
  lat: number;
  lng: number;
  radiusM: number;
  stage: PlannerRolloutStage;
  readinessTier: PlannerReadinessTier;
  plannerVisibility: PlannerVisibility;
  aliasSlugs?: string[];
};

export const PLANNER_VISIBILITY_GATES = {
  minimumPlannableLocations: 250,
  minimumFoodLocations: 120,
  minimumScheduledEvents: 12,
  requiresActiveOfficialEventSource: true,
} as const;

export const PLANNER_33_ROLLOUT: PlannerRolloutCity[] = [
  {
    slug: "berlin-berlin",
    label: "Berlin",
    countryCode: "DE",
    lat: 52.520008,
    lng: 13.404954,
    radiusM: 18000,
    stage: "core",
    readinessTier: "full",
    plannerVisibility: "visible",
  },
  {
    slug: "hamburg-hamburg",
    label: "Hamburg",
    countryCode: "DE",
    lat: 53.551086,
    lng: 9.993682,
    radiusM: 18000,
    stage: "core",
    readinessTier: "full",
    plannerVisibility: "visible",
  },
  {
    slug: "muenchen",
    label: "Muenchen",
    countryCode: "DE",
    lat: 48.137154,
    lng: 11.576124,
    radiusM: 16000,
    stage: "core",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["muenchen-freistaat-bayern", "muenchen-bayern"],
  },
  {
    slug: "koeln",
    label: "Koeln",
    countryCode: "DE",
    lat: 50.9422,
    lng: 6.9578,
    radiusM: 18000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["koeln-nordrhein-westfalen"],
  },
  {
    slug: "frankfurt-am-main",
    label: "Frankfurt am Main",
    countryCode: "DE",
    lat: 50.1106,
    lng: 8.6822,
    radiusM: 16000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["frankfurt-am-main-hessen"],
  },
  {
    slug: "stuttgart",
    label: "Stuttgart",
    countryCode: "DE",
    lat: 48.7775,
    lng: 9.18,
    radiusM: 16000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["stuttgart-baden-wuerttemberg", "stuttgart-baden-w-rttemberg"],
  },
  {
    slug: "duesseldorf",
    label: "Duesseldorf",
    countryCode: "DE",
    lat: 51.2311,
    lng: 6.7724,
    radiusM: 15000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["duesseldorf-nordrhein-westfalen"],
  },
  {
    slug: "leipzig",
    label: "Leipzig",
    countryCode: "DE",
    lat: 51.34,
    lng: 12.375,
    radiusM: 16000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["leipzig-freistaat-sachsen", "leipzig-sachsen"],
  },
  {
    slug: "dresden",
    label: "Dresden",
    countryCode: "DE",
    lat: 51.05,
    lng: 13.74,
    radiusM: 16000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["dresden-sachsen"],
  },
  {
    slug: "hannover",
    label: "Hannover",
    countryCode: "DE",
    lat: 52.3744,
    lng: 9.7386,
    radiusM: 15000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["hannover-niedersachsen"],
  },
  {
    slug: "nuernberg",
    label: "Nuernberg",
    countryCode: "DE",
    lat: 49.4539,
    lng: 11.0775,
    radiusM: 15000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["nuernberg-bayern"],
  },
  {
    slug: "bremen",
    label: "Bremen",
    countryCode: "DE",
    lat: 53.0758,
    lng: 8.8072,
    radiusM: 16000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["bremen-freie-hansestadt-bremen"],
  },
  {
    slug: "dortmund",
    label: "Dortmund",
    countryCode: "DE",
    lat: 51.5139,
    lng: 7.4653,
    radiusM: 17000,
    stage: "top10",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["dortmund-nordrhein-westfalen"],
  },
  {
    slug: "essen",
    label: "Essen",
    countryCode: "DE",
    lat: 51.4556,
    lng: 7.0116,
    radiusM: 15000,
    stage: "wave1",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["essen-nordrhein-westfalen"],
  },
  {
    slug: "bonn",
    label: "Bonn",
    countryCode: "DE",
    lat: 50.7374,
    lng: 7.0982,
    radiusM: 14000,
    stage: "wave1",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["bonn-nordrhein-westfalen"],
  },
  {
    slug: "muenster",
    label: "Muenster",
    countryCode: "DE",
    lat: 51.9624,
    lng: 7.6257,
    radiusM: 14000,
    stage: "wave1",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["muenster-nordrhein-westfalen"],
  },
  {
    slug: "mannheim",
    label: "Mannheim",
    countryCode: "DE",
    lat: 49.4875,
    lng: 8.466,
    radiusM: 14000,
    stage: "wave1",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["mannheim-baden-wuerttemberg", "mannheim-baden-w-rttemberg"],
  },
  {
    slug: "wiesbaden",
    label: "Wiesbaden",
    countryCode: "DE",
    lat: 50.0826,
    lng: 8.24,
    radiusM: 14000,
    stage: "wave1",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["wiesbaden-hessen"],
  },
  {
    slug: "aachen",
    label: "Aachen",
    countryCode: "DE",
    lat: 50.7753,
    lng: 6.0839,
    radiusM: 14000,
    stage: "wave1",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["aachen-nordrhein-westfalen"],
  },
  {
    slug: "karlsruhe",
    label: "Karlsruhe",
    countryCode: "DE",
    lat: 49.0069,
    lng: 8.4037,
    radiusM: 14000,
    stage: "wave1",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["karlsruhe-baden-wuerttemberg", "karlsruhe-baden-w-rttemberg"],
  },
  {
    slug: "duisburg",
    label: "Duisburg",
    countryCode: "DE",
    lat: 51.4344,
    lng: 6.7623,
    radiusM: 15000,
    stage: "wave2",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["duisburg-nordrhein-westfalen"],
  },
  {
    slug: "bochum",
    label: "Bochum",
    countryCode: "DE",
    lat: 51.4818,
    lng: 7.2162,
    radiusM: 14000,
    stage: "wave2",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["bochum-nordrhein-westfalen"],
  },
  {
    slug: "wuppertal",
    label: "Wuppertal",
    countryCode: "DE",
    lat: 51.2562,
    lng: 7.1508,
    radiusM: 15000,
    stage: "wave2",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["wuppertal-nordrhein-westfalen"],
  },
  {
    slug: "bielefeld",
    label: "Bielefeld",
    countryCode: "DE",
    lat: 52.0212,
    lng: 8.5347,
    radiusM: 15000,
    stage: "wave2",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["bielefeld-nordrhein-westfalen"],
  },
  {
    slug: "augsburg",
    label: "Augsburg",
    countryCode: "DE",
    lat: 48.3705,
    lng: 10.8978,
    radiusM: 14000,
    stage: "wave2",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["augsburg-bayern"],
  },
  {
    slug: "braunschweig",
    label: "Braunschweig",
    countryCode: "DE",
    lat: 52.2689,
    lng: 10.5268,
    radiusM: 14000,
    stage: "wave2",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["braunschweig-niedersachsen"],
  },
  {
    slug: "kiel",
    label: "Kiel",
    countryCode: "DE",
    lat: 54.3233,
    lng: 10.1228,
    radiusM: 15000,
    stage: "wave2",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["kiel-schleswig-holstein"],
  },
  {
    slug: "gelsenkirchen",
    label: "Gelsenkirchen",
    countryCode: "DE",
    lat: 51.5177,
    lng: 7.0857,
    radiusM: 14000,
    stage: "wave3",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["gelsenkirchen-nordrhein-westfalen"],
  },
  {
    slug: "moenchengladbach",
    label: "Moenchengladbach",
    countryCode: "DE",
    lat: 51.1805,
    lng: 6.4428,
    radiusM: 14000,
    stage: "wave3",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["moenchengladbach-nordrhein-westfalen"],
  },
  {
    slug: "magdeburg",
    label: "Magdeburg",
    countryCode: "DE",
    lat: 52.1205,
    lng: 11.6276,
    radiusM: 15000,
    stage: "wave3",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["magdeburg-sachsen-anhalt"],
  },
  {
    slug: "freiburg-im-breisgau",
    label: "Freiburg im Breisgau",
    countryCode: "DE",
    lat: 47.999,
    lng: 7.8421,
    radiusM: 14000,
    stage: "wave3",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: [
      "freiburg-im-breisgau-baden-wuerttemberg",
      "freiburg-im-breisgau-baden-w-rttemberg",
    ],
  },
  {
    slug: "luebeck",
    label: "Luebeck",
    countryCode: "DE",
    lat: 53.8655,
    lng: 10.6866,
    radiusM: 14000,
    stage: "wave3",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["luebeck-schleswig-holstein"],
  },
  {
    slug: "erfurt",
    label: "Erfurt",
    countryCode: "DE",
    lat: 50.9787,
    lng: 11.0328,
    radiusM: 14000,
    stage: "wave3",
    readinessTier: "full",
    plannerVisibility: "visible",
    aliasSlugs: ["erfurt-thueringen"],
  },
];

export const PLANNER_33_ROLLOUT_MAP = new Map(
  PLANNER_33_ROLLOUT.map((city) => [city.slug, city] satisfies [string, PlannerRolloutCity])
);

export const PLANNER_VISIBLE_CITY_ROLLOUT = PLANNER_33_ROLLOUT.filter(
  (city) => city.plannerVisibility === "visible"
);

export const PLANNER_VISIBLE_CITY_SLUGS = PLANNER_VISIBLE_CITY_ROLLOUT.map((city) => city.slug);

export const PLANNER_33_CITY_CONFIGS = Object.fromEntries(
  PLANNER_33_ROLLOUT.map((city) => [
    city.slug,
    {
      slug: city.slug,
      label: city.label,
      countryCode: city.countryCode,
      lat: city.lat,
      lng: city.lng,
      radiusM: city.radiusM,
    },
  ])
) as Record<
  string,
  Pick<PlannerRolloutCity, "slug" | "label" | "countryCode" | "lat" | "lng" | "radiusM">
>;

export function getPlannerRolloutCity(slug: string | null | undefined) {
  if (!slug) return null;
  return PLANNER_33_ROLLOUT_MAP.get(slug) ?? null;
}

export function getPlannerRolloutCitiesByStage(stage: PlannerRolloutStage) {
  return PLANNER_33_ROLLOUT.filter((city) => city.stage === stage);
}

export function getPreparedPlannerRolloutCities() {
  return PLANNER_33_ROLLOUT.filter((city) => city.plannerVisibility === "hidden");
}
