export const MAX_RETRIEVAL_CANDIDATES = 300;
export const MAX_RETRIEVAL_CANDIDATES_GENERATE_PLAN = 900;
export const MAX_RETRIEVAL_CANDIDATES_API = 1200;
export const MAX_ROUTE_CANDIDATES = 160;

export const FULLDAY_BUFFER_MIN = 60;
export const PARTIALDAY_BUFFER_MIN = 25;
export const ROUTE_BUFFER_FULLDAY_MIN = 105;
export const ROUTE_BUFFER_PARTIALDAY_MIN = 35;
