import type {
  MonetizationEntitlementDefinition,
  MonetizationProductDefinition,
  SponsoredSlotDefinition,
} from "./types";

export const MONETIZATION_TRUST_RULES = [
  "organic ranking stays separate from sponsored visibility",
  "sponsored placements must be clearly labeled",
  "default activation stays off until product-market fit is proven",
  "creator rewards can start as distribution and credits before cash payouts",
  "b2c premium is selective and should not block the core planner",
] as const;

export const MONETIZATION_ENTITLEMENTS: MonetizationEntitlementDefinition[] = [
  {
    key: "unlimited_saved_plans",
    layer: "consumer",
    defaultState: "off",
    description: "Spaeteres Power-User-Upgrade fuer unbegrenzte Plan-Speicherung.",
  },
  {
    key: "advanced_group_collab",
    layer: "consumer",
    defaultState: "off",
    description: "Erweiterte Gruppenfunktionen und Kollaboration fuer Power User.",
  },
  {
    key: "premium_plan_variants",
    layer: "consumer",
    defaultState: "off",
    description: "Premium-Varianten und tiefere Plan-Versionierung.",
  },
  {
    key: "creator_distribution_tools",
    layer: "creator",
    defaultState: "off",
    description: "Creator-Distribution und spaetere Reward-/Boost-Mechaniken.",
  },
  {
    key: "creator_reward_pool",
    layer: "creator",
    defaultState: "off",
    description: "Belohnungslogik fuer Creator-Performance und Partnerkampagnen.",
  },
  {
    key: "partner_featured_visibility",
    layer: "partner",
    defaultState: "off",
    description: "Featured-Sichtbarkeit fuer zahlende Partner in begrenzten Slots.",
  },
  {
    key: "partner_reporting",
    layer: "partner",
    defaultState: "off",
    description: "Reporting und Kampagnen-Insights fuer Partnerpakete.",
  },
  {
    key: "white_label_access",
    layer: "strategic",
    defaultState: "off",
    description: "White-Label- und Co-Branding-Zugaenge fuer spaetere Lizenzmodelle.",
  },
  {
    key: "insights_exports",
    layer: "strategic",
    defaultState: "off",
    description: "Aggregierte Insight-Exporte fuer spaetere Strategic Revenue Produkte.",
  },
];

export const MONETIZATION_PRODUCTS: MonetizationProductDefinition[] = [
  {
    key: "affiliate_events",
    label: "Affiliate Events",
    horizon: "short_term",
    revenueLayer: "transaction",
    billingModel: "cps",
    targetType: "event",
    notes: "Tickets und Veranstalter",
  },
  {
    key: "affiliate_experiences",
    label: "Affiliate Experiences",
    horizon: "short_term",
    revenueLayer: "transaction",
    billingModel: "cps",
    targetType: "experience",
    notes: "Booking- und Experience-Partner",
  },
  {
    key: "affiliate_restaurants",
    label: "Affiliate Restaurants",
    horizon: "short_term",
    revenueLayer: "transaction",
    billingModel: "cpl",
    targetType: "restaurant",
    notes: "Reservierungs- und Lead-Partner",
  },
  {
    key: "affiliate_tourism",
    label: "Affiliate Tourism",
    horizon: "short_term",
    revenueLayer: "transaction",
    billingModel: "cps",
    targetType: "tourism",
    notes: "Touren und touristische Angebote",
  },
  {
    key: "featured_event",
    label: "Featured Event",
    horizon: "short_term",
    revenueLayer: "visibility",
    billingModel: "fixed_weekly",
    targetType: "event",
    linkedEntitlementKey: "partner_featured_visibility",
    notes: "Begrenzte Event-Sichtbarkeit pro Stadt und Woche",
  },
  {
    key: "featured_location",
    label: "Featured Location",
    horizon: "short_term",
    revenueLayer: "visibility",
    billingModel: "fixed_monthly",
    targetType: "venue",
    linkedEntitlementKey: "partner_featured_visibility",
    notes: "Featured Visibility fuer Restaurants und Venues",
  },
  {
    key: "sponsored_placement",
    label: "Sponsored Placement",
    horizon: "short_term",
    revenueLayer: "visibility",
    billingModel: "hybrid",
    targetType: "partner",
    linkedEntitlementKey: "partner_featured_visibility",
    notes: "CPC plus Mindestbudget in klar markierten Slots",
  },
  {
    key: "city_spotlight",
    label: "City Spotlight",
    horizon: "short_term",
    revenueLayer: "visibility",
    billingModel: "campaign",
    targetType: "city",
    notes: "Saisonale oder kuratierte Themenflaechen",
  },
  {
    key: "partner_basic",
    label: "Partner Basic",
    horizon: "medium_term",
    revenueLayer: "recurring",
    billingModel: "fixed_monthly",
    targetType: "partner",
    linkedEntitlementKey: "partner_reporting",
    notes: "Profil, CTA, Basis-Insights",
  },
  {
    key: "partner_pro",
    label: "Partner Pro",
    horizon: "medium_term",
    revenueLayer: "recurring",
    billingModel: "fixed_monthly",
    targetType: "partner",
    linkedEntitlementKey: "partner_reporting",
    notes: "Sichtbarkeit, Kampagnen, Reporting",
  },
  {
    key: "city_pro_plus",
    label: "City Pro+",
    horizon: "medium_term",
    revenueLayer: "recurring",
    billingModel: "fixed_monthly",
    targetType: "partner",
    linkedEntitlementKey: "partner_reporting",
    notes: "Mehrere Standorte und saisonale Pushes",
  },
  {
    key: "creator_brand_route_distribution",
    label: "Creator / Brand Route Distribution",
    horizon: "medium_term",
    revenueLayer: "recurring",
    billingModel: "campaign",
    targetType: "creator",
    linkedEntitlementKey: "creator_distribution_tools",
    notes: "Monetisierte Distribution fuer Creator- und Brand-Routen",
  },
  {
    key: "b2c_premium",
    label: "B2C Premium",
    horizon: "later",
    revenueLayer: "consumer",
    billingModel: "entitlement",
    targetType: "consumer",
    linkedEntitlementKey: "premium_plan_variants",
    notes: "Selektives Power-User-Upgrade, kein frueher Kern-Paywall",
  },
  {
    key: "white_label_city_guide",
    label: "White-Label City Guide",
    horizon: "long_term",
    revenueLayer: "strategic",
    billingModel: "license",
    targetType: "city",
    linkedEntitlementKey: "white_label_access",
    notes: "Lizenzmodell fuer Staedte und Tourismus",
  },
  {
    key: "media_widget",
    label: "Media Widget / Co-Branding",
    horizon: "long_term",
    revenueLayer: "strategic",
    billingModel: "fixed_monthly",
    targetType: "publisher",
    linkedEntitlementKey: "white_label_access",
    notes: "Medien-Distribution und Co-Branding",
  },
  {
    key: "demand_insights",
    label: "Demand Insights",
    horizon: "long_term",
    revenueLayer: "strategic",
    billingModel: "license",
    targetType: "partner",
    linkedEntitlementKey: "insights_exports",
    notes: "Aggregierte Nachfrage-Insights",
  },
];

export const SPONSORED_SLOT_CATALOG: SponsoredSlotDefinition[] = [
  {
    key: "planner_featured_event_module",
    surface: "planner",
    slotType: "featured_event",
    disclosureLabel: "Featured",
    defaultStatus: "inactive",
    maxPositions: 1,
    notes: "Ein klar markierter Event-Slot in kaufnahen Planner-Momenten",
  },
  {
    key: "planner_featured_location_module",
    surface: "planner",
    slotType: "featured_location",
    disclosureLabel: "Featured",
    defaultStatus: "inactive",
    maxPositions: 1,
    notes: "Ein klar markierter Location-Slot im Planner",
  },
  {
    key: "explore_featured_events_strip",
    surface: "explore",
    slotType: "featured_event",
    disclosureLabel: "Featured",
    defaultStatus: "inactive",
    maxPositions: 3,
    notes: "Featured Event Strip auf Explore-Flaechen",
  },
  {
    key: "explore_featured_locations_strip",
    surface: "explore",
    slotType: "featured_location",
    disclosureLabel: "Featured",
    defaultStatus: "inactive",
    maxPositions: 3,
    notes: "Featured Location Strip auf Explore-Flaechen",
  },
  {
    key: "route_detail_brand_distribution",
    surface: "route_detail",
    slotType: "creator_distribution",
    disclosureLabel: "Partner Route",
    defaultStatus: "inactive",
    maxPositions: 1,
    notes: "Distribution fuer Brand- oder Creator-Routen",
  },
  {
    key: "location_detail_partner_spotlight",
    surface: "location_detail",
    slotType: "featured_location",
    disclosureLabel: "Partner Highlight",
    defaultStatus: "inactive",
    maxPositions: 1,
    notes: "Partner-Sichtbarkeit auf Location-Details",
  },
  {
    key: "event_detail_partner_spotlight",
    surface: "event_detail",
    slotType: "featured_event",
    disclosureLabel: "Partner Highlight",
    defaultStatus: "inactive",
    maxPositions: 1,
    notes: "Partner-Sichtbarkeit auf Event-Details",
  },
  {
    key: "shared_plan_partner_cta",
    surface: "shared_plan",
    slotType: "sponsored_placement",
    disclosureLabel: "Empfohlen",
    defaultStatus: "inactive",
    maxPositions: 1,
    notes: "Kontextnaher CTA-Slot auf Share-Seiten",
  },
  {
    key: "creator_profile_featured_routes",
    surface: "creator_profile",
    slotType: "creator_distribution",
    disclosureLabel: "Featured",
    defaultStatus: "inactive",
    maxPositions: 2,
    notes: "Featured Distribution auf Creator-Profilen",
  },
  {
    key: "city_spotlight_seasonal",
    surface: "city_spotlight",
    slotType: "city_spotlight",
    disclosureLabel: "Spotlight",
    defaultStatus: "inactive",
    maxPositions: 1,
    notes: "Saisonale Themen- oder Stadt-Spotlights",
  },
];
